const fs = require('fs');

const langs = ['en', 'fr', 'pt', 'ar', 'sw', 'ha'];

const additions = {
  en: {
    "project_not_found": "Project not found",
    "back_to_home": "Back to Home",
    "pending_consensus": "Pending Consensus",
    "awaiting_audit": "Awaiting Audit",
    "expert_audited": "Expert Audited",
    "ai_discovered": "AI Discovered",
    "community_added": "Community Added",
    "government": "Government",
    "evidence_gallery": "Evidence Gallery",
    "add_evidence": "Add Evidence",
    "lat": "LAT",
    "lng": "LNG",
    "exif_verified": "EXIF Verified",
    "awaiting_evidence": "Awaiting Community Evidence",
    "needs_evidence": "This project needs photographic evidence. If you are near the site, capture a geo-tagged photo to earn community reputation.",
    "verify_capture": "Verify Location & Capture Evidence",
    "ai_analysis": "AI Budget Analysis",
    "deliverables": "Required Deliverables",
    "attached_sources": "Attached Sources",
    "verification_trail": "Verification Trail",
    "citizen_upload": "Citizen Upload",
    "media_anchored": "Media & EXIF data anchored",
    "community_consensus": "Community Consensus",
    "gathering_votes": "Gathering votes...",
    "oracle_audit": "Oracle Audit",
    "signature_verified": "Expert cryptographic signature verified",
    "awaiting_assignment": "Awaiting expert assignment",
    "signed_by": "Signed by:",
    "upvotes": "Upvotes",
    "downvotes": "Downvotes"
  },
  fr: {
    "project_not_found": "Projet introuvable",
    "back_to_home": "Retour à l'accueil",
    "pending_consensus": "Consensus en attente",
    "awaiting_audit": "En attente d'audit",
    "expert_audited": "Audité par un expert",
    "ai_discovered": "Découvert par l'IA",
    "community_added": "Ajouté par la communauté",
    "government": "Gouvernement",
    "evidence_gallery": "Galerie de preuves",
    "add_evidence": "Ajouter une preuve",
    "lat": "LAT",
    "lng": "LNG",
    "exif_verified": "EXIF vérifié",
    "awaiting_evidence": "En attente de preuves de la communauté",
    "needs_evidence": "Ce projet a besoin de preuves photographiques. Si vous êtes près du site, capturez une photo géolocalisée.",
    "verify_capture": "Vérifier la position et capturer",
    "ai_analysis": "Analyse budgétaire IA",
    "deliverables": "Livrables requis",
    "attached_sources": "Sources jointes",
    "verification_trail": "Piste de vérification",
    "citizen_upload": "Téléchargement citoyen",
    "media_anchored": "Média et données EXIF ancrés",
    "community_consensus": "Consensus de la communauté",
    "gathering_votes": "Collecte des votes...",
    "oracle_audit": "Audit Oracle",
    "signature_verified": "Signature cryptographique vérifiée",
    "awaiting_assignment": "En attente d'affectation d'un expert",
    "signed_by": "Signé par:",
    "upvotes": "Votes pour",
    "downvotes": "Votes contre"
  },
  pt: {
    "project_not_found": "Projeto não encontrado",
    "back_to_home": "Voltar ao Início",
    "pending_consensus": "Consenso Pendente",
    "awaiting_audit": "Aguardando Auditoria",
    "expert_audited": "Auditado por Especialista",
    "ai_discovered": "Descoberto por IA",
    "community_added": "Adicionado pela Comunidade",
    "government": "Governo",
    "evidence_gallery": "Galeria de Evidências",
    "add_evidence": "Adicionar Evidência",
    "lat": "LAT",
    "lng": "LNG",
    "exif_verified": "EXIF Verificado",
    "awaiting_evidence": "Aguardando Evidência da Comunidade",
    "needs_evidence": "Este projeto precisa de evidência fotográfica. Se você estiver perto do local, tire uma foto com geotag.",
    "verify_capture": "Verificar Localização e Capturar",
    "ai_analysis": "Análise de Orçamento IA",
    "deliverables": "Entregáveis Necessários",
    "attached_sources": "Fontes Anexadas",
    "verification_trail": "Trilha de Verificação",
    "citizen_upload": "Upload do Cidadão",
    "media_anchored": "Mídia e dados EXIF ancorados",
    "community_consensus": "Consenso da Comunidade",
    "gathering_votes": "Reunindo votos...",
    "oracle_audit": "Auditoria Oracle",
    "signature_verified": "Assinatura criptográfica verificada",
    "awaiting_assignment": "Aguardando atribuição de especialista",
    "signed_by": "Assinado por:",
    "upvotes": "Votos a favor",
    "downvotes": "Votos contra"
  },
  ar: {
    "project_not_found": "المشروع غير موجود",
    "back_to_home": "العودة إلى الرئيسية",
    "pending_consensus": "في انتظار الإجماع",
    "awaiting_audit": "في انتظار التدقيق",
    "expert_audited": "تم تدقيقه من قبل خبير",
    "ai_discovered": "اكتشف بواسطة الذكاء الاصطناعي",
    "community_added": "أضيف من قبل المجتمع",
    "government": "الحكومة",
    "evidence_gallery": "معرض الأدلة",
    "add_evidence": "إضافة دليل",
    "lat": "خط العرض",
    "lng": "خط الطول",
    "exif_verified": "تم التحقق من EXIF",
    "awaiting_evidence": "في انتظار أدلة المجتمع",
    "needs_evidence": "يحتاج هذا المشروع إلى أدلة فوتوغرافية. التقط صورة جغرافية الموقع إذا كنت قريباً.",
    "verify_capture": "التحقق من الموقع والتقاط صورة",
    "ai_analysis": "تحليل ميزانية الذكاء الاصطناعي",
    "deliverables": "المخرجات المطلوبة",
    "attached_sources": "المصادر المرفقة",
    "verification_trail": "مسار التحقق",
    "citizen_upload": "تحميل المواطن",
    "media_anchored": "الوسائط وبيانات EXIF مثبتة",
    "community_consensus": "إجماع المجتمع",
    "gathering_votes": "جاري جمع الأصوات...",
    "oracle_audit": "تدقيق أوراكل",
    "signature_verified": "تم التحقق من التوقيع التشفيري للخبير",
    "awaiting_assignment": "في انتظار تعيين خبير",
    "signed_by": "موقّع من:",
    "upvotes": "تصويتات إيجابية",
    "downvotes": "تصويتات سلبية"
  },
  sw: {
    "project_not_found": "Mradi haujapatikana",
    "back_to_home": "Rudi Mwanzo",
    "pending_consensus": "Makubaliano Yanasubiriwa",
    "awaiting_audit": "Inasubiri Ukaguzi",
    "expert_audited": "Imekaguliwa na Mtaalam",
    "ai_discovered": "Imegunduliwa na AI",
    "community_added": "Imeongezwa na Jamii",
    "government": "Serikali",
    "evidence_gallery": "Matunzio ya Ushahidi",
    "add_evidence": "Ongeza Ushahidi",
    "lat": "LAT",
    "lng": "LNG",
    "exif_verified": "EXIF Imethibitishwa",
    "awaiting_evidence": "Inasubiri Ushahidi wa Jamii",
    "needs_evidence": "Mradi huu unahitaji ushahidi wa picha. Kama uko karibu na eneo, piga picha yenye eneo kijiografia.",
    "verify_capture": "Thibitisha Eneo & Piga Picha",
    "ai_analysis": "Uchambuzi wa Bajeti wa AI",
    "deliverables": "Matokeo Yanayohitajika",
    "attached_sources": "Vyanzo Vilivyoambatanishwa",
    "verification_trail": "Njia ya Uthibitishaji",
    "citizen_upload": "Upakiaji wa Raia",
    "media_anchored": "Vyombo vya habari na EXIF vimeunganishwa",
    "community_consensus": "Makubaliano ya Jamii",
    "gathering_votes": "Inakusanya kura...",
    "oracle_audit": "Ukaguzi wa Oracle",
    "signature_verified": "Saini ya mtaalam imethibitishwa",
    "awaiting_assignment": "Inasubiri upangaji wa mtaalam",
    "signed_by": "Imesainiwa na:",
    "upvotes": "Kura za ndio",
    "downvotes": "Kura za hapana"
  },
  ha: {
    "project_not_found": "Ba a sami aikin ba",
    "back_to_home": "Koma Gida",
    "pending_consensus": "Ana jiran amincewa",
    "awaiting_audit": "Ana Jiran Bincike",
    "expert_audited": "Masanin Ya Bincika",
    "ai_discovered": "AI Ya Gano",
    "community_added": "Al'umma Sun Kara",
    "government": "Gwamnati",
    "evidence_gallery": "Tarihin Shaida",
    "add_evidence": "Kara Shaida",
    "lat": "LAT",
    "lng": "LNG",
    "exif_verified": "An Tabbatar da EXIF",
    "awaiting_evidence": "Ana Jiran Shaidar Al'umma",
    "needs_evidence": "Wannan aikin yana bukatar shaidar hoto. Idan kana kusa, dauki hoton wuri.",
    "verify_capture": "Tabbatar Wuri & Dauki Shaida",
    "ai_analysis": "Binciken Kasafin Kudin AI",
    "deliverables": "Abubuwan Da Ake Bukata",
    "attached_sources": "Majiyoyin Da Aka Makala",
    "verification_trail": "Tarihin Tabbatarwa",
    "citizen_upload": "Saka Hoton Dan Kasa",
    "media_anchored": "An Adana Bayanan Hoton",
    "community_consensus": "Amincewar Al'umma",
    "gathering_votes": "Ana Tattara kuri'u...",
    "oracle_audit": "Binciken Oracle",
    "signature_verified": "An Tabbatar da sa hannun masani",
    "awaiting_assignment": "Ana jiran ba masani aikin",
    "signed_by": "Sa hannun:",
    "upvotes": "Yabo",
    "downvotes": "Suka"
  }
};

langs.forEach(lang => {
  const filePath = `messages/${lang}.json`;
  let data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
  data.ProjectDetails = { ...data.ProjectDetails, ...additions[lang] };
  fs.writeFileSync(filePath, JSON.stringify(data, null, 2));
});
console.log("Updated project details strings!");
